name: 'Dyno CLI'
description: 'Interact with Dyno'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'
    - name: Get OS and arch info
      run: |
        GOOSARCH='linux/amd64'
        GOOS=${GOOSARCH%/*}
        GOARCH=${GOOSARCH#*/}
      shell: bash
    - name: Build
      run: |
        go build -o dyno main.go
        dyno -h
      shell: bash
