name: 'Dyno CLI'
description: 'Interact with Dyno'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: go env -w GO111MODULE=auto
      shell: bash
    - run: cat main.go
      shell: bash
    - run: cd /usr/local/bin
      shell: bash
