name: 'Dyno CLI'
description: 'Interact with Dyno'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: thatisuday/go-cross-build@v1
      with:
          platforms: 'linux/amd64, darwin/amd64, windows/amd64'
          package: '${{ github.action_path }}'
          name: 'dyno'
          compress: 'true'
          dest: '${{ github.action_path }}'
          
      - run: ./dyno -h
        shell: bash
