name: 'Dyno CLI'
description: 'Interact with Dyno'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'
    - run: echo ${{ github.action_path }}
      shell: bash
    - run: go env -w GO111MODULE=auto
      shell: bash
    - run: .${{ github.action_path }}/dyno -h
      shell: bash
